import { Product } from './type';

export const products: Product[] = [
  // ── QASA ──────────────────────────────────────────────────────────
  { id:1,  name:'QASA Auto Voltage Regulator 1000VA', brand:'QASA', category:'Stabilizers',
    price:18500, rating:4.6, reviews:89, badge:'Popular', badgeColor:'#f59e0b',
    imgPath:'./imgs/Stabilizer.jpg',inStock:true,
    models:['500VA','1000VA','2000VA','5000VA'],
    description:'Automatic voltage regulator protecting your appliances from power surges and fluctuations.' },
  { id:2,  name:'QASA 18" Standing Fan', brand:'QASA', category:'Fans',
    price:22000, oldPrice:26000, rating:4.5, reviews:134, badge:'Sale', badgeColor:'#df0000',
    imgPath:'./imgs/NoSolarFan.jpg', inStock:true, models:['16"','18"'] },
  { id:3,  name:'QASA AC/DC Rechargeable Solar Fan 18"', brand:'QASA', category:'Solar Fans',
    price:48000, oldPrice:55000, rating:4.8, reviews:213, badge:'Best Seller', badgeColor:'#003dad',
    imgPath:'./imgs/Fan18.jpg', inStock:true, models:['12"','16"','18"'],
    description:'Works on both AC power and solar/battery. Perfect for power outages.' },
  { id:4,  name:'QASA Rechargeable LED Lamp', brand:'QASA', category:'Rechargeable Lamps',
    price:8500, rating:4.3, reviews:67,
    imgPath:'./imgs/Lamp.jpg', inStock:true, models:['Small','Medium','Large'] },
  { id:5,  name:'QASA Steam Iron 2200W', brand:'QASA', category:'Irons',
    price:14500, rating:4.4, reviews:52,
    imgPath:'./imgs/IRON.jpg', inStock:true },
  { id:6,  name:'QASA Washing Machine 6kg Top Load', brand:'QASA', category:'Washing Machines',
    price:95000, oldPrice:110000, rating:4.5, reviews:38, badge:'Sale', badgeColor:'#df0000',
    imgPath:'./imgs/QWM.jpg', inStock:true, models:['6kg','8kg'] },
  { id:7,  name:'QASA 2-Slice Toaster', brand:'QASA', category:'Toasters',
    price:12000, rating:4.2, reviews:45,
    imgPath:'./imgs/toaster.jpg', inStock:true },
  { id:8,  name:'QASA Electric Yam Pounder 1000W', brand:'QASA', category:'Yam Pounders',
    price:32000, rating:4.7, reviews:187, badge:'Popular', badgeColor:'#f59e0b',
    imgPath:'./imgs/pounder.jpg', inStock:true, models:['1000W 5L','1500W 7L'],
    description:'Powerful electric yam pounder. No more manual pounding.' },
  { id:9,  name:'QASA Blender 1.5L 600W', brand:'QASA', category:'Blenders',
    price:16500, rating:4.3, reviews:72,
    imgPath:'./imgs/blender.jpg', inStock:true, models:['600W','800W'] },
  { id:10, name:'QASA Electric Pressure Cooker 6L', brand:'QASA', category:'Pressure Cookers',
    price:28000, rating:4.5, reviews:56,
    imgPath:'./imgs/cooker.jpg', inStock:true, models:['4L','6L','8L'] },
  { id:11, name:'QASA Electric Kettle 1.7L 2200W', brand:'QASA', category:'Electric Kettles',
    price:11500, rating:4.4, reviews:93,
    imgPath:'./imgs/Kettle.jpg', inStock:true },
  { id:12, name:'QASA Electric Gas Cooker 4 Burner', brand:'QASA', category:'Electric Cookers',
    price:85000, rating:4.6, reviews:41,
    imgPath:'./imgs/QGC.jpg', inStock:true, models:['2 Burner','4 Burner'] },
  { id:13, name:'QASA Microwave Oven 20L', brand:'QASA', category:'Microwaves',
    price:38000, rating:4.4, reviews:34,
    imgPath:'./imgs/QGC.jpg', inStock:true, models:['20L','25L'] },
  { id:14, name:'QASA Solar Inverter 1500W', brand:'QASA', category:'Solar Appliances',
    price:145000, rating:4.7, reviews:28, badge:'New', badgeColor:'#09f5a6',
    imgPath:'./imgs/Inverter.jpg', inStock:true,
    models:['1500W','3000W','5000W'],
    description:'Complete solar inverter solution. Keep your home powered 24/7.' },
  { id:15, name:'QASA Dish Rack Stainless Steel', brand:'QASA', category:'Dish Racks',
    price:7500, rating:4.1, reviews:23,
    imgPath:'./imgs/Rack.jpg', inStock:true },
  // ── HISENSE ───────────────────────────────────────────────────────
  { id:16, name:'Hisense 43" 4K Smart TV A7 Series', brand:'Hisense', category:'TVs',
    price:185000, oldPrice:210000, rating:4.7, reviews:156, badge:'Sale', badgeColor:'#df0000',
    imgPath:'./imgs/H43.jpg', inStock:true,
    models:['32"','43"','55"','65"'],
    description:'4K UHD Android Smart TV with built-in Google Assistant.' },
  { id:17, name:'Hisense 55" QLED 4K Smart TV U7', brand:'Hisense', category:'TVs',
    price:385000, rating:4.8, reviews:89, badge:'Premium', badgeColor:'#4800c5',
    imgPath:'./imgs/H55.jpg', inStock:true, models:['55"','65"','75"'] },
  { id:18, name:'Hisense Standing Fan 18"', brand:'Hisense', category:'Fans',
    price:28000, rating:4.4, reviews:67,
    imgPath:'./imgs/HFan.jpg', inStock:true, models:['16"','18"'] },
  { id:19, name:'Hisense Split AC 1.5HP Inverter', brand:'Hisense', category:'Air Conditioners',
    price:285000, rating:4.6, reviews:112, badge:'Popular', badgeColor:'#f59e0b',
    imgPath:'./imgs/HiAC.jpg', inStock:true,
    models:['1HP','1.5HP','2HP','2.5HP'],
    description:'Energy-saving inverter AC with quick cooling technology.' },
  { id:20, name:'Hisense Front Load Washing Machine 8kg', brand:'Hisense', category:'Washing Machines',
    price:245000, rating:4.5, reviews:43,
    imgPath:'./imgs/HWM8KG.jpg', inStock:true, models:['6kg','8kg','10kg'] },
  // ── LG ────────────────────────────────────────────────────────────
  { id:21, name:'LG 43" 4K UHD Smart TV UR80', brand:'LG', category:'TVs',
    price:420000, rating:4.7, reviews:98,
    imgPath:'./imgs/LG45.jpg', inStock:true,
    models:['43"','50"','55"','65"'] },
  { id:22, name:'LG 55" OLED 4K evo Smart TV', brand:'LG', category:'TVs',
    price:680000, rating:4.9, reviews:34, badge:'Premium', badgeColor:'#4800c5',
    imgPath:'./imgs/LG55.jpg', inStock:true,
    models:['55"','65"','77"'],
    description:'Stunning OLED display with perfect blacks and vivid colors.' },
  { id:23, name:'LG Front Load Washing Machine 9kg', brand:'LG', category:'Washing Machines',
    price:320000, rating:4.7, reviews:67, badge:'New', badgeColor:'#09f5a6',
    imgPath:'./imgs/WM9KG.jpg', inStock:true, models:['7kg','9kg','12kg'] },
  { id:24, name:'LG Microwave Oven 25L Solo', brand:'LG', category:'Microwaves',
    price:98000, rating:4.5, reviews:52,
    imgPath:'./imgs/MWAVELG.jpg', inStock:true, models:['20L','25L','32L'] },
  // ── QLINK ─────────────────────────────────────────────────────────
  { id:25, name:'Qlink 16" Standing Fan', brand:'Qlink', category:'Fans',
    price:18500, rating:4.3, reviews:45,
    imgPath:'./imgs/qlink2.jpg', inStock:true, models:['12"','16"','18"'] },
  { id:26, name:'Qlink Ceiling Fan 52"', brand:'Qlink', category:'Fans',
    price:24000, rating:4.4, reviews:38,
    imgPath:'./imgs/qlink1.jpg', inStock:true, models:['42"','52"','56"'] },
];

export const categories = [
  { name:'Smart TVs',          brands:'LG · Hisense',           imgGradient:'linear-gradient(135deg,#080f1e,#1a2848)', img:'./imgs/TV.jpg' },
  { name:'Fans',               brands:'QASA · Qlink · Hisense', imgGradient:'linear-gradient(135deg,#e0f0ff,#a0d0f0)', img:'./imgs/Fan.jpg' },
  { name:'Air Conditioners',   brands:'Hisense · Samsung',                 imgGradient:'linear-gradient(135deg,#e0f8f4,#60d8cc)', img:'./imgs/AC.jpg' },
  { name:'Washing Machines',   brands:'QASA · LG · Hisense',    imgGradient:'linear-gradient(135deg,#f0f0ff,#b8b8f8)', img:'./imgs/Samsung.jpg' },
  { name:'Kitchen Appliances', brands:'QASA',                    imgGradient:'linear-gradient(135deg,#fff0e0,#f8c070)', img:'./imgs/KitchenAppliance.jpg' },
  { name:'Solar Appliances',   brands:'QASA',                    imgGradient:'linear-gradient(135deg,#0a1a08,#1a3818)', img:'./imgs/Solar.jpg' },
  { name:'Smart Watches',      brands:'QASA',                    imgGradient:'linear-gradient(135deg,#fffbe8,#f0d870)', img:'./imgs/SmartWatch.jpg' },
  { name:'Fridges & Cookers',  brands:'QASA',                    imgGradient:'linear-gradient(135deg,#ffeef0,#f8a0b0)', img:'./imgs/Fridge.png' },
];

export const brands = [
  { id:'qasa',    name:'QASA',    tagline:'16 categories', bg:'linear-gradient(135deg,#1a0808,#2e1010)', logo:'./logos/QASA.png',    textColor:'#c0392b', light:false },
  { id:'hisense', name:'Hisense', tagline:'4 categories',  bg:'linear-gradient(135deg,#006b5e,#009688)', logo:'./logos/hisense-logo.svg', textColor:'#fff',    light:false },
  { id:'lg',      name:'LG',      tagline:'3 categories',  bg:'linear-gradient(135deg,#7a001c,#a50034)', logo:'./logos/lg-mono.svg',           textColor:'#fff',    light:false },
  { id:'samsung', name:'SAMSUNG', tagline:'Coming soon',   bg:'linear-gradient(135deg, #111111, #141414)', logo:'./logos/samsung-mono.svg', textColor:'#fff',    light:false },
  { id:'qlink',   name:'QLINK',   tagline:'2 categories',  bg:'linear-gradient(135deg,#d0d0d0,#e8e8e8)', logo:'./logos/Qlink-logo.jpg',   textColor:'#2a2a2a', light:true  },
];

export const heroSlides = [
  { headline:'Five trusted brands.\nOne destination.',
    sub:'QASA, Hisense, LG, Samsung and Qlink — everything your home needs, all in one place.',
    cta:'Shop now', ctaSecondary:'Browse brands', bg:'#06090f', accent:'#1a6bff' },
  { headline:'Built for Nigerian homes.\nPriced for Nigerian pockets.',
    sub:'Quality appliances that match our climate, our kitchens and our lifestyle. Delivered to all 36 states.',
    cta:'Browse products', ctaSecondary:'View categories', bg:'#0a0d12', accent:'#10b92c' },
  { headline:"Power outage?\nWe've got you covered.",
    sub:"Rechargeable fans, solar appliances and inverters from QASA — keeping your home running when NEPA doesn't.",
    cta:'Shop solar', ctaSecondary:'Learn more', bg:'#060f0a', accent:'#f59e0b' },
  { headline:'Order today.\nDelivered to your door.',
    sub:'Secure checkout via Paystack. Fast nationwide delivery handled by our logistics partners.',
    cta:'Start shopping', ctaSecondary:'How it works', bg:'#06090f', accent:'#4800c5' },
];